### PR TITLE
Update to waf 1.9.13

### PR DESCRIPTION
**Pull request by khancyr**
Just rebase to the lastest stable revision

### CODE REVIEW

**Comment by OXINARF** [comment]
@khancyr Have you tested this extensively with ArduPilot? What is the drive behind this update? Just for the sake of having last version?

**Comment by magicrub** [comment]
ping @lucasdemarchi

**Comment by lucasdemarchi** [comment]
If this is a rebase, you need to keep the old reference on the server, otherwise we will have trouble to checkout a commit before this going in.

**Comment by guludo** [comment]
A tag like `waf-1.9.2.ap` would suffice. I agree that this should be tested before going in.

**Pull request merged**
